# Generated by Django 4.1.4 on 2022-12-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_complete',
            field=models.BooleanField(default=False),
        ),
    ]
