version: '3.9'

services:
  django:
    build: .
    image: todo-backend
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    env_file:
#      - ./.env
      - ./todo/.env
#    environment:
#      POSTGRES_PASSWORD:
    ports:
      - 5436:5432
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  todo_postgres_data:

networks:
  default:
    name: todo-network
    external: true